ARG IMAGE_TAG=16
FROM node:$IMAGE_TAG

ARG USERNAME
ARG GROUP
ARG ROOT_PASS
ARG HOME=/home/${USERNAME}

RUN for arg in ROOT_PASS USERNAME GROUP; \
  do \
  [ ! -z "${arg}" ] || { echo "ARG \"$arg\" needs to be set"; exit 1; } \
  done;

RUN echo "root:$ROOT_PASS" | chpasswd

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  git \
  jq \
  libc6 \
  libgcc-s1 \
  wget 

# Neovim requires manual retrieval of the latest version
# as the apt package is quite old
RUN wget https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb \
  -O /neovim.deb
RUN apt install -y /neovim.deb 
RUN rm /neovim.deb
ENV EDITOR=nvim

USER $USERNAME

# Gists
ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/create-env-example.sh \
  /scripts/create-env-example.sh
ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/3523b00578807d63b05399fe57a4b2a7/raw/.bashrc \
  $HOME/.bashrc
ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/d5c216c744460c45bf6260d0de4131b4/raw/.inputrc \
  $HOME/.inputrc
RUN chmod +x \
  /scripts/create-env-example.sh \
  $HOME/.bashrc \
  $HOME/.inputrc

COPY src/scripts /scripts

RUN mkdir -p $HOME/.vscode-server/extensions
RUN mkdir -p $HOME/.vscode-server-insiders/extensions
