ARG USERNAME=
ARG GROUP=
ARG ROOT_PASS=
ARG BASE_IMAGE=node

FROM $BASE_IMAGE

RUN for arg in BASE_IMAGE ROOT_PASS USERNAME GROUP; \
  do \
  [ ! -z "${arg}" ] || { echo "ARG \"$arg\" needs to be set"; exit 1; } \
  done;

RUN echo "root:$ROOT_PASS" | chpasswd

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  git \
  vim

USER $USERNAME

# Gists
ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/3eb6693a91b1aa5b3863d087de1d189b72eeeec8/create-env-example.sh \
  /scripts/create-env-example.sh
ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/3523b00578807d63b05399fe57a4b2a7/raw/7df99dbbeb8ee4d14396be043aef4fbf8fb42ce5/.bashrc \
  /home/$USERNAME/.bashrc
ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/d5c216c744460c45bf6260d0de4131b4/raw/d227102e3630a93f8eafcb4d2a5a053d2ae04415/.inputrc \
  /home/$USERNAME/.inputrc
RUN chmod +x \
  /scripts/create-env-example.sh \
  /home/$USERNAME/.bashrc \
  /home/$USERNAME/.inputrc
