name: Push

on:
  push

jobs:
  push:
    uses: ./.github/workflows/build.wfc.yml
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    